<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_CloudflareTurnstile
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>
<div class="checkbox mb-3">
    <!-- The following line controls and configures the Turnstile widget. -->
    <div class="cf-turnstile" data-sitekey="<?= /*noEscape*/ $block->escapeHtml($block->getSiteKey()); ?>"
     data-theme="light"></div>
    <!-- end. -->
</div>